spring:
  application:
    name: SpringAI
  ai:
    google:
      genai:
        api-key: ${MY_GOOGLE_AI_API_KEY}
        embedding:
          api-key: ${MY_GOOGLE_AI_API_KEY}
          text:
            options:
              model: gemini-embedding-001
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.9
            thinking-budget: 128
#            thinking-level: LOW
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen3:4b
logging:
  level:
    org.springframework.ai.chat.client: DEBUG

