spring:
  application:
    name: SpringAI
  ai:
    google:
      genai:
        api-key: ${my-google-ai-api-key}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.9
            thinking-budget: 128
#            thinking-level: LOW
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen3:4b
logging:
  level:
    org.springframework.ai.chat.client: DEBUG

